In [1]:
# Импортируем объект Counter из модуля collections
from collections import Counter
# Создаём пустой объект Counter
c = Counter()

In [3]:
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']
c = Counter(cars)
print(c)
print(c['black'])
print(sum(c.values()))

print(c.values())
# dict_values([3, 2, 3, 1])

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})
3
9
dict_values([3, 2, 3, 1])


In [13]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]
from collections import defaultdict
groups = defaultdict(list)
for student, group in students:
    groups[group].append(student)
 
print(groups)


defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})


In [17]:
from collections import OrderedDict
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
ordered_client_ages = OrderedDict(data)
print(ordered_client_ages)
# По результатам 3 повторов получились вот такие результаты:
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])

OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])


In [ ]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]
from collections import defaultdict
groups = defaultdict(list)
for student, group in students:
    groups[group].append(student)
 
print(groups)


defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})


In [11]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
 
print(counter_moscow)
print(counter_spb)
print(counter_moscow + counter_spb)
counter_moscow.subtract(counter_spb)
print(counter_moscow)

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})
Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})
Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


In [12]:
print(*counter_moscow.elements())
print(list(counter_moscow))
print(counter_moscow.most_common(2))

black black yellow
['black', 'white', 'yellow', 'red']
[('black', 2), ('yellow', 1)]


In [18]:
import sys
print(sys.version)

3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]


In [19]:
from collections import deque
dq = deque()
print(dq)
clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print(clients)
# deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])


print(clients[2])
# Smirnov
first_client = clients.popleft()
second_client = clients.popleft()
 
print("First client:", first_client)
print("Second client:", second_client)
print(clients)

tired_client = clients.pop()
print(tired_client, "left the queue")
print(clients)

tired_client = clients.pop()
print(tired_client, "left the queue")
print(clients)

shop = deque([1, 2, 3, 4, 5])
print(shop)
# deque([1, 2, 3, 4, 5])
shop.extend([11, 12, 13, 14, 15, 16, 17])
print(shop)

shop = deque([1, 2, 3, 4, 5])
print(shop)
# deque([1, 2, 3, 4, 5])
shop.extendleft([11, 12, 13, 14, 15, 16, 17])
print(shop)

deque([])
deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
Smirnov
First client: Ivanov
Second client: Petrov
deque(['Smirnov', 'Tikhonova'])
Tikhonova left the queue
deque(['Smirnov'])
Smirnov left the queue
deque([])
deque([1, 2, 3, 4, 5])
deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])
deque([1, 2, 3, 4, 5])
deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5])


In [20]:
limited = deque(maxlen=3)
print(limited)
# deque([], maxlen=3)
 
limited_from_list = deque([1,3,4,5,6,7], maxlen=3)
print(limited_from_list)

limited.extend([1,2,3])
print(limited)
# deque([1, 2, 3], maxlen=3)
 
print(limited.append(8))
# None
print(limited)
# deque([2, 3, 8], maxlen=3)

deque([], maxlen=3)
deque([5, 6, 7], maxlen=3)
deque([1, 2, 3], maxlen=3)
None
deque([2, 3, 8], maxlen=3)


In [21]:
import numpy as np

In [24]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [25]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [35]:
import numpy as np
arr = np.array([1,5,2,9,10])
print(arr.dtype)
arr

int32


array([ 1,  5,  2,  9, 10])

In [33]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [36]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [37]:
arr = np.float64(arr)
arr

array([ 1.,  5.,  2.,  9., 10.])

In [39]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
arr

array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

In [43]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

arr.ndim
# 1
nd_arr.ndim
# 2
arr.size
# 5
nd_arr.size
# 9


arr.shape
# (5,)
nd_arr.shape
# (3, 3)
arr.itemsize
# 1
nd_arr.itemsize
# 2

2

In [44]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
# (5, 4, 3)

(5, 4, 3)


In [49]:
np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])
np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)
arr = np.linspace(1, 2, 10)
arr
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)

0.45


In [50]:
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])


arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new
# array([[0, 2, 4, 6],
#       [1, 3, 5, 7]])

arr_trans = arr.transpose()
arr_trans
# array([[0, 4],
#        [1, 5],
#        [2, 6],
#        [3, 7]])

array([0, 1, 2, 3, 4, 5, 6, 7])